# Generated by Django 4.2.9 on 2025-04-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_pic'),
        ('accounts', '0003_user_profile_pic'),
    ]

    operations = [
    ]
