# Generated by Django 5.2 on 2025-04-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'vehicle type',
                'verbose_name_plural': 'vehicle types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, unique=True, verbose_name='license plate')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='nickname')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='registration number')),
                ('registration_expiry', models.DateField(blank=True, null=True, verbose_name='registration expiry')),
                ('is_insured', models.BooleanField(default=False, verbose_name='is insured')),
                ('insurance_provider', models.CharField(blank=True, max_length=100, verbose_name='insurance provider')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='insurance policy number')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='insurance expiry')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vehicle_qrcodes', verbose_name='QR code')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehicletype')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('emission_test', 'Emission Test'), ('tax_receipt', 'Tax Receipt'), ('other', 'Other')], default='other', max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('document_file', models.FileField(upload_to='vehicle_documents', verbose_name='document file')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vehicle_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vehicle document',
                'verbose_name_plural': 'vehicle documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
