# Generated by Django 4.2.9 on 2025-04-10 22:21

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20250410_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
