# Generated by Django 4.2.9 on 2025-04-10 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0005_vehicleowner_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleowner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
