# Generated by Django 5.2 on 2025-04-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True, verbose_name='camera ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('capture_interval', models.IntegerField(default=5, verbose_name='capture interval (seconds)')),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='authentication token')),
                ('latitude', models.FloatField(default=0.0, verbose_name='latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='longitude')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('connecting', 'Connecting'), ('online', 'Online'), ('error', 'Error')], default='offline', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_capture_time', models.DateTimeField(blank=True, null=True, verbose_name='last capture time')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'traffic camera',
                'verbose_name_plural': 'traffic cameras',
                'ordering': ['-last_capture_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camera_captures/%Y/%m/%d/', verbose_name='captured image')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('plate_detected', models.BooleanField(default=False, verbose_name='plate detected')),
                ('detected_plate_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='detected plate text')),
                ('confidence', models.FloatField(default=0.0, verbose_name='confidence')),
                ('detection_time', models.FloatField(default=0.0, verbose_name='detection time (seconds)')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='cameras.trafficcamera', verbose_name='camera')),
            ],
            options={
                'verbose_name': 'camera capture',
                'verbose_name_plural': 'camera captures',
                'ordering': ['-timestamp'],
            },
        ),
    ]
