# Generated by Django 5.2 on 2025-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcamera',
            name='coordinates_lat',
            field=models.FloatField(default=0.0, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='coordinates_lng',
            field=models.FloatField(default=0.0, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='trafficcamera',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='trafficcamera',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='latitude (legacy)'),
        ),
        migrations.AlterField(
            model_name='trafficcamera',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='longitude (legacy)'),
        ),
    ]
