# Generated by Django 5.2 on 2025-04-06 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='location name')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='longitude')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('is_popular', models.BooleanField(default=False, verbose_name='is popular location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='route_plann_latitud_6c872a_idx'), models.Index(fields=['is_popular'], name='route_plann_is_popu_6ee3db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='distance (km)')),
                ('normal_duration_minutes', models.PositiveIntegerField(verbose_name='normal duration (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='route_planner.location', verbose_name='destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='route_planner.location', verbose_name='origin')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_datetime', models.DateTimeField(verbose_name='travel datetime')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='is favorite')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='route_planner.location', verbose_name='destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='route_planner.location', verbose_name='origin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'route recommendation',
                'verbose_name_plural': 'route recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('fastest', 'Fastest'), ('shortest', 'Shortest'), ('alternative', 'Alternative')], max_length=20, verbose_name='route type')),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='total distance (km)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(verbose_name='estimated duration (minutes)')),
                ('route_data', models.JSONField(help_text='JSON containing the full route details', verbose_name='route data')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='route_planner.routerecommendation', verbose_name='recommendation')),
            ],
            options={
                'verbose_name': 'recommended route',
                'verbose_name_plural': 'recommended routes',
            },
        ),
        migrations.CreateModel(
            name='RouteTrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], verbose_name='day of week')),
                ('hour_of_day', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], verbose_name='hour of day')),
                ('traffic_factor', models.DecimalField(decimal_places=2, help_text='Multiplier for travel time. 1.0 = normal, 2.0 = twice as long', max_digits=4, verbose_name='traffic factor')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='route_planner.route', verbose_name='route')),
            ],
            options={
                'verbose_name': 'route traffic data',
                'verbose_name_plural': 'route traffic data',
            },
        ),
        migrations.CreateModel(
            name='TrafficJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe')], max_length=20, verbose_name='severity')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_jams', to='route_planner.location', verbose_name='location')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_jams', to=settings.AUTH_USER_MODEL, verbose_name='reported by')),
            ],
            options={
                'verbose_name': 'traffic jam',
                'verbose_name_plural': 'traffic jams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='route_plann_origin__65c0a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination')},
        ),
        migrations.AddIndex(
            model_name='routetrafficdata',
            index=models.Index(fields=['route', 'day_of_week', 'hour_of_day'], name='route_plann_route_i_d7249d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routetrafficdata',
            unique_together={('route', 'day_of_week', 'hour_of_day')},
        ),
        migrations.AddIndex(
            model_name='trafficjam',
            index=models.Index(fields=['is_active'], name='route_plann_is_acti_9ab363_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficjam',
            index=models.Index(fields=['severity'], name='route_plann_severit_3d7d8a_idx'),
        ),
    ]
