# Generated by Django 5.2 on 2025-04-06 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('stripe', 'Credit/Debit Card (Stripe)'), ('khalti', 'Khalti'), ('esewa', 'eSewa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='stripe', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='transaction ID')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='receipt number')),
                ('receipt_url', models.URLField(blank=True, verbose_name='receipt URL')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe session ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe payment intent ID')),
                ('khalti_token', models.CharField(blank=True, max_length=255, verbose_name='Khalti token')),
                ('esewa_reference_id', models.CharField(blank=True, max_length=255, verbose_name='eSewa reference ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('failure', 'Failure'), ('refund', 'Refund'), ('error', 'Error'), ('warning', 'Warning')], default='info', max_length=20, verbose_name='log type')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'payment log',
                'verbose_name_plural': 'payment logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, verbose_name='receipt number')),
                ('receipt_data', models.JSONField(default=dict, verbose_name='receipt data')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='PDF file')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'payment receipt',
                'verbose_name_plural': 'payment receipts',
                'ordering': ['-generated_at'],
            },
        ),
    ]
