{pkgs}: {
  deps = [
    pkgs.qhull
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.glibcLocales
    pkgs.unzip
    pkgs.rustc
    pkgs.pkg-config
    pkgs.libiconv
    pkgs.cargo
    pkgs.libmysqlclient
    pkgs.libGLU
    pkgs.libGL
    pkgs.tesseract
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.postgresql
    pkgs.openssl
  ];
}
