# Generated by Django 5.2 on 2025-04-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('base_fine', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base fine')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe')], default='medium', max_length=20, verbose_name='severity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'violation type',
                'verbose_name_plural': 'violation types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='violation_evidence', verbose_name='evidence image')),
                ('license_plate_image', models.ImageField(blank=True, null=True, upload_to='license_plates', verbose_name='license plate image')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='fine amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('appealed', 'Appealed'), ('appeal_approved', 'Appeal Approved'), ('appeal_rejected', 'Appeal Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('appeal_reason', models.TextField(blank=True, verbose_name='appeal reason')),
                ('appeal_date', models.DateTimeField(blank=True, null=True, verbose_name='appeal date')),
                ('appeal_decision', models.TextField(blank=True, verbose_name='appeal decision')),
                ('appeal_decision_date', models.DateTimeField(blank=True, null=True, verbose_name='appeal decision date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_decisions', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='vehicles.vehicle')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'verbose_name': 'violation',
                'verbose_name_plural': 'violations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='violations.violation')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
