# Generated by Django 4.2.9 on 2025-04-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationtype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='penalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
